---
# The ovnconfig config file. Used by both node and master processes.
kind: ConfigMap
apiVersion: v1
metadata:
  name: ovnkube-config
  namespace: openshift-ovn-kubernetes
data:
  ovnkube.conf:   |-
    [default]
    mtu="{{.OVNConfig.MTU}}"
    cluster-subnets={{.ClusterCIDR}}
    encap-port="6081"
    enable-lflow-cache=false
    lflow-cache-limit-kb=870

    [kubernetes]
    service-cidrs={{.ServiceCIDR}}
    ovn-config-namespace="openshift-ovn-kubernetes"
    kubeconfig={{.KubeconfigPath}}
    host-network-namespace="openshift-host-network"
    platform-type="BareMetal"

    [ovnkubernetesfeature]
    enable-egress-ip=false
    enable-egress-firewall=false
    enable-egress-qos=false

    [gateway]
    mode=local
    nodeport=true

    [masterha]
    election-lease-duration=137
    election-renew-deadline=107
    election-retry-period=26
