---
# setup-microshift-host default vars

# Pin RHEL to a specific version during upgrades (e.g., "9.6")
# Leave undefined to upgrade to the latest available version
# rhel_target_version: "9.6"

go_arch: arm64
go_files:
  - go
  - gofmt
go_version: 1.24.4
go_install_dir: /usr/local/go{{ go_version }}

install_packages:
  - avahi-tools
  - bash-completion
  - firewalld
  - git
  - golang
  - jq
  - lvm2
  - make
  - openshift-clients
  - python3-firewall
  - perf
  - rpm-build
  - selinux-policy-devel 
  - tar
  - vnstat

default_vg_name: microshift
vg_name: "{{ default_vg_name }}"
lvm_disk: /dev/xvdb
