apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sriov-network-config-daemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sriov-network-config-daemon
subjects:
- kind: ServiceAccount
  name: sriov-network-config-daemon
  namespace: sriov-network-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sriov-network-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sriov-network-operator
subjects:
- kind: ServiceAccount
  name: sriov-network-operator
  namespace: sriov-network-operator
