apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sriov-network-config-daemon
  namespace: sriov-network-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sriov-network-config-daemon
subjects:
- kind: ServiceAccount
  name: sriov-network-config-daemon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sriov-network-operator
  namespace: sriov-network-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sriov-network-operator
subjects:
- kind: ServiceAccount
  name: sriov-network-operator
