apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: sriov-network-config-daemon
  namespace: sriov-network-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: sriov-network-operator
  namespace: sriov-network-operator
