apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 0000_50_olm_00-catalogsources.crd.yaml
  - 0000_50_olm_00-clusterserviceversions.crd.yaml
  - 0000_50_olm_00-installplans.crd.yaml
  - 0000_50_olm_00-namespace.yaml
  - 0000_50_olm_00-olmconfigs.crd.yaml
  - 0000_50_olm_00-operatorconditions.crd.yaml
  - 0000_50_olm_00-operatorgroups.crd.yaml
  - 0000_50_olm_00-operators.crd.yaml
  - 0000_50_olm_00-packageserver.pdb.yaml
  - 0000_50_olm_00-pprof-config.yaml
  - 0000_50_olm_00-pprof-rbac.yaml
  - 0000_50_olm_00-pprof-secret.yaml
  - 0000_50_olm_00-subscriptions.crd.yaml
  - 0000_50_olm_01-networkpolicies.yaml
  - 0000_50_olm_02-olm-operator.serviceaccount.yaml
  - 0000_50_olm_03-olmconfig.yaml
  - 0000_50_olm_03-services.yaml
  - 0000_50_olm_07-olm-operator.deployment.yaml
  - 0000_50_olm_08-catalog-operator.deployment.yaml
  - 0000_50_olm_09-aggregated.clusterrole.yaml
  - 0000_50_olm_13-operatorgroup-default.yaml
  - 0000_50_olm_15-csv-viewer.rbac.yaml
