
images:
  - name: caikit-tgis-image
    newName: quay.io/modh/caikit-tgis-serving
    digest: sha256:2c7eef73708b5d73de33153459ac7238fdcf517cdc3544c775981f5814b4b6ed
  - name: caikit-standalone-image
    newName: quay.io/modh/caikit-nlp
    digest: sha256:ada8949b81e646809101edfc76738eb5aac362f783eb2facc8aeed21c7c1512f
  - name: tgis-image
    newName: quay.io/modh/text-generation-inference
    digest: sha256:aebf545d8048a59174f70334dc90c6b97ead4602a39cb7598ea68c8d199168a2
  - name: ovms-image
    newName: quay.io/modh/openvino_model_server
    digest: sha256:53b7fcf95de9b81e4c8652d0bf4e84e22d5b696827a5d951d863420c68b9cfe8
  - name: vllm-cuda-image
    newName: quay.io/modh/vllm
    digest: sha256:4f550996130e7d16cacb24ca9a2865e7cf51eddaab014ceaf31a1ea6ef86d4ec
  - name: vllm-cpu-image
    newName: quay.io/modh/vllm
    digest: sha256:881495befb6f807fa6e55f24e820fa67022b57d8ce0022305d89abe799c490fa
  - name: vllm-gaudi-image
    newName: quay.io/modh/vllm
    digest: sha256:af6a071be36d8a99476f145d1589d7ede97d2760b93335b14ca26de7417e438c
  - name: vllm-rocm-image
    newName: quay.io/modh/vllm
    digest: sha256:7e1d1985b0dd2b5ba2df41fc9c8c3edf13a2d9ed8a4d84db8f00eb6c753bc5c5
