
images:
  - name: caikit-tgis-image
    newName: quay.io/modh/caikit-tgis-serving
    digest: sha256:1d8a9fdd510020ed43ab19f333763257ca8bb1be9dcb330469baa7b110d8a6c8
  - name: caikit-standalone-image
    newName: quay.io/modh/caikit-nlp
    digest: sha256:7af5cfa5617723fc9039a01189e6e5e8d8d1d507cd015442588083a386618843
  - name: tgis-image
    newName: quay.io/modh/text-generation-inference
    digest: sha256:aebf545d8048a59174f70334dc90c6b97ead4602a39cb7598ea68c8d199168a2
  - name: ovms-image
    newName: quay.io/modh/openvino_model_server
    digest: sha256:428c00232cbf3b38a3929a0d22d0e13c6388ce353e3853cc2956d175eacf6724
  - name: vllm-cuda-image
    newName: quay.io/modh/vllm
    digest: sha256:e3e0f4ba3b78b53b3754bf63baf53bf22d9ec22fdc2974d4f2b5bdf8aeab276b
  - name: ray-tls-generator-image
    newName: registry.redhat.io/ubi9/ubi-minimal:latest
    digest: registry.redhat.io/ubi9/ubi-minimal:latest
  - name: vllm-cpu-image
    newName: quay.io/modh/vllm
    digest: sha256:9e5f8f4394f599befb9e7f703e30581c4d7f062b8d4974992d6222837977ca5e
  - name: vllm-gaudi-image
    newName: quay.io/modh/vllm
    digest: sha256:e7cba648377c6fa29fab30481f97d96ccca76498aaf8bcf5162c74dfa4e0100c
  - name: vllm-rocm-image
    newName: quay.io/modh/vllm
    digest: sha256:de5d71c4fb6add81a01171bbabcd2e65fc2d75f0d6e57ca9ebcad9b4084db420
