
images:
  - name: ray-tls-generator-image
    newName: registry.redhat.io/ubi9/ubi-minimal:latest
    digest: registry.redhat.io/ubi9/ubi-minimal:latest
  - name: caikit-tgis-image
    newName: quay.io/opendatahub/caikit-tgis-serving:fast
    digest: quay.io/opendatahub/caikit-tgis-serving:fast
  - name: caikit-standalone-image
    newName: quay.io/opendatahub/caikit-nlp:fast
    digest: quay.io/opendatahub/caikit-nlp:fast
  - name: tgis-image
    newName: quay.io/modh/text-generation-inference
    digest: sha256:8419f73485c75b4eb0095d31879cc1a94e2be38a0ece08bc7923cef9cdd9444a
  - name: ovms-image
    newName: quay.io/opendatahub/openvino_model_server:2025.1-release
    digest: quay.io/opendatahub/openvino_model_server:2025.1-release
  - name: vllm-cuda-image
    newName: quay.io/opendatahub/vllm:fast
    digest: quay.io/opendatahub/vllm:fast
  - name: vllm-cpu-image
    newName: quay.io/opendatahub/vllm:fast-cpu
    digest: quay.io/opendatahub/vllm:fast-cpu
  - name: vllm-gaudi-image
    newName: quay.io/opendatahub/vllm:fast-gaudi
    digest: quay.io/opendatahub/vllm:fast-gaudi
  - name: vllm-rocm-image
    newName: quay.io/opendatahub/vllm:fast-rocm
    digest: quay.io/opendatahub/vllm:fast-rocm
  - name: vllm-spyre-image
    newName: registry.redhat.io/rhaiis/vllm-spyre-rhel9
    digest: sha256:f36864ec0d7a18a3143296ba2e624eca1fa6ba0af87a7196b325384785bbcf4b
  - name: guardrails-detector-huggingface-runtime-image
    newName: quay.io/trustyai/guardrails-detector-huggingface-runtime:latest
    digest: quay.io/trustyai/guardrails-detector-huggingface-runtime:latest
