
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:0fa62f63b7b2b1303fe6058c1f4f15223ec4391f404c08f7832110a0e8c58d26
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:1203e9f2b45f759865a80214a440fab276c8eb04ee98b0a15596be456d4badf2
