
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:75829232db202e7de8b66b8b441c91e9ff52398c720d5844981681d3d2d1448c
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:1d0ec8b66586bb011937b434794d56fe2d4d5f3fdff0a92ddf1cfbce58dcf356
