
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:97971a15175ad753d500f2e6b8b51e11e8012dbcecba93b199165092a41386cc
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:8f9755834d53a34693aec23bc9ad196f7fe965040b3bccaa6b747abf128253b7
