
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:89667da77c3be3d4e6487ee1e928d16add7bfdca00e05857af442692af2d0b27
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:e94a0ae6348298a9e9a1616a3c478877f2cd2720ff4898130d634aa00d2a81d2
