
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:9d198c91a901305431cc0c33d4693bffb8dc37b2c40790daefce52093c2197b3
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:e080632a43141ece7ba812fbf64ec9d08e625b97804cf8481df8b5f1c9c6b0ce
