
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:26965b6179c2914b617f3a6cd413d0143a9c4ea275377444ba5a5595fb188c7a
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:dc2cca14180b6add6a2e66489bc126603e337d974a961bf7a770adb47b424034
