
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:38e5ee99714488b76fcc8227e6e8d21be9e1ea0ba65d1efc624706ae2b1de961
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:8e31d64a528362808991067ce390f9e8f6d41f60e1a49e6a6bc9b663898fa591
