
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:321b2924d459d534f7982e825a46ab6471f3b67e9fdc668ce7aa3e247848eb3f
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:34691b9a2ae1c6158ef6d128d497c1bbf11a773c394287593d446e29af59d87e
