
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:6bd8e4e1fc36f9a248416caf2033c1d2187af55a9c8342757bfd4b6b9171d27d
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:7889025b3220a9afd19f698a169840d7288fb6f43d260947f0eecdebbc79de17
