
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:897af15512a83b063bfef713029ede645a782ff1b97c18534b179ab47ed733d4
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:2eb91fa7a57db0aab2a7c8750209e16a0f1760be6e8d54de77f67b206a2534b0
