
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:101744da99d01de50cf59f2475fe29bd573de938ac83ac2c3dd1a829df9efde3
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:a6156cd43526414afefe3728890dd3f9b68f7ff0ed2d3089cf328d3d8f7c04fa
