
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:10afbd255b3bb7048aa2f51bafa9764146282600e42e18c233078c71586c776f
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:6a1ae8cae17d65291e2bb3a4483df68cca5c0c81633130852bb9955cb22e2cea
