
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:311510bffe8b47715a73c04679def6b6e78752b8363f4076ea5464376e34dd4f
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:58f5756ed5085a92f323651af967418be5c1d136a94bfbf68a78d8d29f79b644
