
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:48621ef6f52720ee8898d43e1cc3f9172107f7f5e5a47ba71486d556c09b66f5
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:02df0468d57b1a660c66e4b34bd1d4a747482e69e173c8d5a61506527af48eaa
