
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:2c9f3befe925a25f6859ce8ea69da2721c9cae8ee5cc0682e42c78ac102f425a
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:cce21af5cdce8e943f962089e1d304dd2d9b573eeff0a8bbbf5f610ed1d90c25
