
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:3c9448c78d676d323f410a678b804667306dbff92f9187b395eda46e4343b4e2
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:7eeb9ee393f88cde73dc537d20de0d8b5beaa28221d89dc552483477c8691228
