
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:c717e464f8eb9b62738f009caf81d3bff797b1fa4504d6bfe68563aa2896a3ca
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:daa028fd713e3ceebaf533f53918619f405013f6bef46b9fad8f569c11fba519
