
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:f8aec9d2b954482c24a141facb8834f22ed7009e9098dca3ab13b4436483b488
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:c7041673dfe0d6a23864466bbfb458c78525261e586c260cc4db6286abc689da
