
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:af893a82961ed03fc2be07907b006177917a6a0dd1b3b91179fe1803db98a7f6
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:9f43bbdb3f50b6824b0cd3f7a520f0115170eec517dc5ca3fdd918f854594a99
