
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:339e6c637393961f0ddfaff015fa9030a9abdb75a1d24c20da064793a97cee0b
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:875caf9302b320c9fd41be71ba0be0aab15765048e6847dd231cee5819d5348a
