
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:be14424807c85bcdb57721e7c80303e1ce501a840952fb9ad95e7dcc8c0cf055
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:999b7a384217919bfdb2e333dc03569f9a85d8a3a47ace345cf6630a9b144a10
