
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:6cc8354ae22397bc2d52f3fc35bea7ed49392184a6bfb4ef522f98e71a184251
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:43802f3ee739768c8f40ac924cb3df15fbfbfca21c8ab6005ddc65800e7fe3b0
