
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:691401e54870ddc8490a2d1c582a765f54bb2e7e30b75d1f98744c98656c89ce
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:51f25ba11f77453a71e8a502e9839c6925bbc924d4d4a5723a6a2dc754740572
