
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:c4cce2168e1541aa6699e38960b1ff4a49ac8dd7a17106c3c9f96a2944adef0f
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:62c28b81a8c23179ea8cc5c491276d7da5cb888f17f5ac5d29391b2f0e599f72
