
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:f6f4a03fcc90675209b8c8df00f131084fb3f3eb1f2fd08f693ca500839bf81b
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:78139568d47eb2911a0441712c26b968514a72b29dd24facec31e99629035f58
