
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:8688debacf215c769cd90f4db01be854fe6ec7c8d3c715c2abab4aad79f21f5b
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:49c3797fb00465b61f4b0d4a28a3bb29df6500d0796522ec67f40f45bc853747
