
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:0befe272d970d3a60b8411270d98a8431be6db82bc6987476e7965c019ff765d
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:dccc3bc8b1d44cf1f7712036883a794cef517848921d1430869019cba422e029
