
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:46cadf5f862d2a99a8080e2ea1f2dab83a256de441cf3e75737d722b56e7716f
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:2a8e7d7b6d9a9911dd83e4dd24a2ce92de77cef6e391fa6c1f24ed1da3f919a3
