---
# create-vm default vars

vm_name: microshift-dev
vm_disk_dir: /var/lib/libvirt/images
iso_file: /var/lib/libvirt/images/rhel-9.4-x86_64-dvd.iso
num_cpu: 4
ram_size: 8
disk_size: 60
swap_size: 8
data_volume_size: 2
