apiVersion: apps/v1
kind: Deployment
metadata:
  name: topolvm-controller
  namespace: openshift-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: topolvm-controller
      app.kubernetes.io/name: topolvm-csi-driver
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: topolvm-controller
        app.kubernetes.io/name: topolvm-csi-driver
      name: topolvm-controller
      namespace: openshift-storage
    spec:
      containers:
      - command:
        - /topolvm-controller
        - --cert-dir=/certs
        image: '{{ .ReleaseImage.topolvm_csi }}'
        startupProbe:
          failureThreshold: 60
          periodSeconds: 2
          httpGet:
            port: healthz
            path: /healthz
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 3
        name: topolvm-controller
        ports:
        - containerPort: 9808
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8080
            scheme: HTTP
        resources:
          requests:
            cpu: 2m
            memory: 31Mi
        volumeMounts:
        - mountPath: /run/topolvm
          name: socket-dir
        - mountPath: /certs
          name: certs
      - args:
        - --csi-address=/run/topolvm/csi-topolvm.sock
        - --enable-capacity
        - --capacity-ownerref-level=2
        - --capacity-poll-interval=30s
        - --feature-gates=Topology=true
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: '{{ .ReleaseImage.topolvm_csi_provisioner }}'
        name: csi-provisioner
        resources:
          requests:
            cpu: 2m
            memory: 35Mi
        volumeMounts:
        - mountPath: /run/topolvm
          name: socket-dir
      - args:
        - --csi-address=/run/topolvm/csi-topolvm.sock
        image: '{{ .ReleaseImage.topolvm_csi_resizer }}'
        name: csi-resizer
        resources:
          requests:
            cpu: 1m
            memory: 23Mi
        volumeMounts:
        - mountPath: /run/topolvm
          name: socket-dir
      - args:
        - --csi-address=/run/topolvm/csi-topolvm.sock
        image: '{{ .ReleaseImage.topolvm_csi_livenessprobe }}'
        name: liveness-probe
        resources:
          requests:
            cpu: 1m
            memory: 9Mi
        volumeMounts:
        - mountPath: /run/topolvm
          name: socket-dir
      - name: csi-snapshotter
        image: '{{ .ReleaseImage.csi_external_snapshotter }}'
        args:
        - "--v=5"
        - "--csi-address=$(ADDRESS)"
        - "--leader-election=false"
        env:
        - name: ADDRESS
          value: /csi/csi-topolvm.sock
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      initContainers:
      - command:
        - /usr/bin/bash
        - -c
        - openssl req -nodes -x509 -newkey rsa:4096 -subj '/DC=self_signed_certificate'
          -keyout /certs/tls.key -out /certs/tls.crt -days 3650
        image: '{{ .ReleaseImage.openssl }}'
        name: self-signed-cert-generator
        resources: {}
        volumeMounts:
        - mountPath: /certs
          name: certs
      serviceAccountName: topolvm-controller
      volumes:
      - emptyDir: {}
        name: socket-dir
      - emptyDir: {}
        name: certs
