name: npm-update-pf
on:
  schedule:
    - cron: '0 2 * * 1'
  # can be run manually on https://github.com/cockpit-project/starter-kit/actions
  workflow_dispatch:
jobs:
  npm-update:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y npm make

      - name: Set up configuration and secrets
        run: |
          printf '[user]\n\tname = Cockpit Project\n\temail=cockpituous@gmail.com\n' > ~/.gitconfig
          echo '${{ secrets.GITHUB_TOKEN }}' > ~/.config/github-token

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Run npm-update bot
        run: |
          make bots
          bots/npm-update @patternfly
