---
# quick-microshift-boot tasks - measures warm boot time

- name: measure microshift service boot time
  include_tasks: roles/common/tasks/boot.yml
  vars:
    boot_output_filename: "{{ boot_output_filename }}"
    cleanup_microshift: "{{ cleanup_microshift }}"
    reboot: "{{ reboot }}"
