
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:fc7ab65f8e3c25b9ef771e31af1623e0895af82c85962969da1793bba9bbb07e
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:ed9948ccacc95b391b46c5ab54db0bef05d4e868b05682a8da8bfb280f7ede52
