
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:353f8d91d668176e3a52bd8615d3dbf86b3ac0c9af25574c01fddbd34f95531e
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:227657eee17b72b9127c0ba7cb7796c3a88f08b86cff574bd7fcb00bae4c0c7b
