
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:bbe3f967bbfde6d7673116cf018d1fb77e774edcde42c469fa453f9323eaedb1
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:5d69edc977280d4e041d7e2a7dfe9d1feb8b79691868ba8323cf1b9f63535d88
