
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:ac8f62653277b14ebfdbbfa5d0846207ea3cc205d0010ad3de8567cbedac5f9c
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:f59f60b8e50062cbc22a133f05dbfe39dabfb71f5eacf91946321db68eb34ec6
