
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:ee0a068a5dddaac0144c7b7232cbd0c2705ae0764fb6ccad6c00a2d1cc895cb8
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:b67ff492b5d46df49a67f8b9288f66a52c963b93da567d71f61776e86dd1f220
