
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:c626150f07ba75062856d06674f8c419ae002930de38821811236c2445f1c1b5
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:3aa55b454c43ad80dfa5df489a795e0635845b10db18aec4f9a06cc5f869d5da
