
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:0479630609cbae7913b6053e3ad392e7dfa114088c5c0044acfdb447392cffef
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:6aeed20b8cd24c342bd24a92364c8fce56d1d34797a16be7ab8db9dbf2d7cf0f
