
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:9d1ad997536ac5fd07f014961fad4cdcb5d92f8bf64797cd3a7fa54fe629ac25
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:e8d77f789c1fb1d08cf5b8e51ce08155b4d10a23a80feb76e22cfb007ccb44d8
