
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:6f8349603015cf0c13bb8185ead002157c3f956c2cc58b66a6ba7a8d6b82f80d
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:1dec54facc83db32616d21fe570728884ed94ab289bc573c511c196ad802a20f
