
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:44d35f9f3775bde52498e1150b5d63b6833736cf920ae60c687300a6e437539a
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:e27a0bf7c7baf59fa68dc528d072a381ee1dd2a136d037e462f85d0355146b6f
