
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:d2dc1c89ab53ad2ef09460e1d83019cc6516ac8b7c19070fa4fb0b7b24f1f6c6
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:b034a65c871afe1b4142e336b6b9810e964aa93bdadec29413d003ba845f7d6f
