
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:1db300a8daf4cc3bec029fcb58827a8c2ee4eafb79079e48acad03aa5576fb3c
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:ff28003cec4096537ed48224129015e04ace560f928953027830356320880cca
