
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:f84a81280262040d7ed2d1488bf8d1acad4a3715cb01d42aabd45838bb94652a
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:8f78e04f538471f090b20a27c034123c54b037ec3aa80fc1263387d7926eefef
