
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:12d4bbcf3c53c2697c487746d8c7e1f6a575bf03e0912a45d9cb78f678716a63
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:0d16f87b20a9ebf784518a9e191531f8eaeaf4d803a15b8e5939253dbc2af7ac
