
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:ae956f5a3b5f7921c3073012f8f558e5de30670b75035f587c95c30e3dcdf538
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:7c4c97088416dcd1947472990be3ec1f112ebebe6eef74c3dcbdc0b583a4ad16
