
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:0f7c43082b5805baba35257cce05f677374f2854b142d7a643f49247a12ef73e
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:500120d5d94fbbfd1ddb146d9a66b9408c5a5122c4f75d5bd1b59e20a712ad01
