
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:4025a8f6a76f61f8a9f2f84121bfedbbe8ff41de68f82b299076edbfd3088afa
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:6e5fa36908d6a837ace0805cb4cb076cac2985038f827993df5e2455592b1d01
