
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:241291831d9b4c48e0c169fa0bdb93ff828457caff66727da046d0465bac8565
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:0ca176c383308b28a57ea234dd4136d69e3721b68dc451d3b84bdd4dac366a98
