
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:3c49d07ed89e92a610d29a7abb57c196781605002351ea6cbec935a17562c672
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:4ae5789cba6a7efa255c09f5eff28def415cd2060518a6f3f2de97d4d26d7df3
