
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:54f5034a18aa0b2508a627bae9c8073e5370ef7234d722426d2bd0ab63522938
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:f3f1d86a100a6b93a4faafab39d0a1527a7fbb83e55850479960666bc12b5848
