
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:8a0c279857e021f68166d9e7aeab249e805db042cafb03d4cbbcc7e7f6432af5
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:7952c16491f47948dcba9c3192f546e49d9203c92d2640a7b84169b37f5b20a1
