
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:4fe03201cbe47e09a6084d70da2333e97feff80c75e1ffdbc17165d8835d8a00
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:a7a8669f6845691a50e0efeef410ed89e214c614fc0b5361cc5f0e276030bd49
