
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:7827f4f5db81db17764dcce294cf1445671377388925a69935249240535d66eb
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:cefe433cbb7086fe5f04b2b68d7404c39743e5748d2af18c56b96354cb7f69a5
