
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:35fbdf8b8b9e02f2faf2165465cc1661b18cdcce05bc85576ba5f4b958d4fe26
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:2b2eaa6cb89cdb9f43020ecbc7c8a1db00282864513b9195da12fc3e4a95f847
