
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:f866a3522335d552e202e4e9ed37c41d2417441d7cf1562eb9429c2813cb7359
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:d04b6e8115c268cf7b9bd5f90e3d80ebfde9592e42672fa7fee255b71739f632
