
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:a8da3e3eeacc80e7064f7d0baf820d7f4bf63bc639e6b6da3eb66480b84f6dc4
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:7a70760e40a5e888b6e9a6c62b17a40ffad74fff27fd46338677450c95f5e842
