
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:344e242a8de27735f6a6b04b07db6aa2d1279b302dd6eef12d976212f5d549b8
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:57007fab893d47c884189d5806fa6da3718d46e2fb8aca347c08ced09d676817
