
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:e45a823c96517d642e654ff09c07f01f87a24adb900946fa1b76ede88c803b28
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:b3005530b0fe7da09e408fda796a13ecd6f963671adcb70e03e98fb09130abe7
