
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:76d38a43ab2285bd44fff7afdd869a627780d4cecf02e14871c4b6b1611f26a6
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:86fdde740202fd1be36991c650fdc2920ef65255c53b98c7e229b595bee6c313
