
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:2eec024b9c11a6467b35887df6b16ccff66614cdd76e5f8a7002d9b586441de1
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:dedcb767db43fff70e86f157d3c24d6eb067fbc29084bc5ff18165677d3d9571
