
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:deb2eebaeff01d5ad4241313aa7295163a27d0b87694ef2dc3b0ea7ef6587eee
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:359850b757cc59b0bb60793c065c77aaca7cfa185989b06bfdf01a005cb6cccf
