
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:6e0b7b592258d528fbe5c464b2ae5794af0af407195d42b894d172d3b5776fbb
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:bc72b13124f3f69514ea87a0e74575c6f91b8ec9f92faec908849b4321d9c349
