
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:e11862ce9d85213da2e5ff0086a7dae2d89dc68fabde4b5feab44802ab37dfff
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:9405f714f22de66eea01e771505c006912d1516bb36c63b77d9432a66a5d112d
