
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:e0420d92c6151f4f9b64ba218105b3477ee30deb04234ff7f34717831c34403d
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:faf6dd53d1ecc777b182fce23bb5f4d13a42fe830f0b87c50334e9ebbe3c2bdd
