# https://github.com/jekyll/minima

domain: microshift.io # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://microshift.io # the base hostname and protocol for your site, e.g. http://example.com
title: MicroShift
description: MicroShift is a research project that is exploring how OpenShift Kubernetes can be optimized for small form factor and edge computing.
type: website
keep_files: ["CNAME"]
repository: redhat-et/microshift
exclude: ["vendor"]

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: "syntax"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-sitemap
  - premonition
  - jekyll-toc

minima:
   skin: dark
   social_links:
     github: redhat-et

header_pages:
  - index.md
  - design/design.md
  - microshift-aio/README.md
  - microshift-containerized/README.md
  - known-issues.md

toc:
  min_level: 2 # default: 1
  max_level: 6 # default: 6
