apiVersion: v1
kind: Service
metadata:
  labels:
    app: microweb
  name: microweb
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: microweb
  sessionAffinity: None
  type: ClusterIP

