name: release

# only execute a release when triggered manually
on:
  workflow_dispatch:

env:
  RELEASE_REG_USER: ${{ secrets.REGISTRY_USER }}
  RELEASE_REG_PASS: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Install required packages
        run: sudo apt-get update && sudo apt install build-essential qemu-user qemu-user-static 
      
      - name: Checkout source
        uses: actions/checkout@v2
      
      - name: execute release.sh
        shell: bash
        run: make release TOKEN=${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
