name: Validate Ubuntu
on:
  push:
    branches: ["main", "release*"]
    tags: ["*"]
  pull_request:
    branches: ["main", "release*"]

env:
  GO_VERSION: "1.16"

jobs:
  build-microshift:
    name: Build-Microshift
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install required packages
        run: sudo apt install build-essential

      - name: Checkout
        uses: actions/checkout@v2    

      - name: make
        run: make build

      - name: save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: microshift
          path: ./microshift
